-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for user tasks (quests)
create table user_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task_id text not null, -- ID from Tarkov.dev API
  completed boolean default false,
  completed_at timestamp with time zone default timezone('utc'::text, now()),
  
  unique(user_id, task_id)
);

alter table user_tasks enable row level security;

create policy "Users can view their own tasks." on user_tasks
  for select using (auth.uid() = user_id);

create policy "Users can insert their own tasks." on user_tasks
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own tasks." on user_tasks
  for update using (auth.uid() = user_id);
  
create policy "Users can delete their own tasks." on user_tasks
  for delete using (auth.uid() = user_id);


-- Create a table for user hideout progress
create table user_hideout (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  station_id text not null, -- ID from Tarkov.dev API
  level int not null,
  completed boolean default false, -- true if this level is constructed
  updated_at timestamp with time zone default timezone('utc'::text, now()),

  unique(user_id, station_id, level)
);

alter table user_hideout enable row level security;

create policy "Users can view their own hideout." on user_hideout
  for select using (auth.uid() = user_id);

create policy "Users can insert their own hideout." on user_hideout
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own hideout." on user_hideout
  for update using (auth.uid() = user_id);

create policy "Users can delete their own hideout." on user_hideout
  for delete using (auth.uid() = user_id);

-- Set up Realtime for these tables
alter publication supabase_realtime add table profiles;
alter publication supabase_realtime add table user_tasks;
alter publication supabase_realtime add table user_hideout;
